# Generated by Django 2.2.6 on 2019-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_file', models.FileField(upload_to='')),
                ('invitees', models.FileField(upload_to='')),
            ],
        ),
    ]
